<?php declare(strict_types=1);

namespace Mkioschi\Enums;

enum Country: string implements EnumContract
{
    case AFGHANISTAN = 'AF';
    case ALBANIA = 'AL';
    case ALGERIA = 'DZ';
    case AMERICAN_SAMOA = 'AS';
    case ANDORRA = 'AD';
    case ANGOLA = 'AO';
    case ANGUILLA = 'AI';
    case ANTARCTICA = 'AQ';
    case ANTIGUA_AND_BARBUDA = 'AG';
    case ARGENTINA = 'AR';
    case ARMENIA = 'AM';
    case ARUBA = 'AW';
    case AUSTRALIA = 'AU';
    case AUSTRIA = 'AT';
    case AZERBAIJAN = 'AZ';
    case BAHAMAS = 'BS';
    case BAHRAIN = 'BH';
    case BANGLADESH = 'BD';
    case BARBADOS = 'BB';
    case BELARUS = 'BY';
    case BELGIUM = 'BE';
    case BELIZE = 'BZ';
    case BENIN = 'BJ';
    case BERMUDA = 'BM';
    case BHUTAN = 'BT';
    case BOLIVIA = 'BO';
    case BONAIRE_SINT_EUSTATIUS_AND_SABA = 'BQ';
    case BOSNIA_AND_HERZEGOVINA = 'BA';
    case BOTSWANA = 'BW';
    case BOUVET_ISLAND = 'BV';
    case BRAZIL = 'BR';
    case BRITISH_INDIAN_OCEAN_TERRITORY = 'IO';
    case BRUNEI_DARUSSALAM = 'BN';
    case BULGARIA = 'BG';
    case BURKINA_FASO = 'BF';
    case BURUNDI = 'BI';
    case CABO_VERDE = 'CV';
    case CAMBODIA = 'KH';
    case CAMEROON = 'CM';
    case CANADA = 'CA';
    case CAYMAN_ISLANDS = 'KY';
    case CENTRAL_AFRICAN_REPUBLIC = 'CF';
    case CHAD = 'TD';
    case CHILE = 'CL';
    case CHINA = 'CN';
    case CHRISTMAS_ISLAND = 'CX';
    case COCOS_KEELING_ISLANDS = 'CC';
    case COLOMBIA = 'CO';
    case COMOROS = 'KM';
    case CONGO_KINSHASA = 'CD';
    case CONGO_BRAZZAVILLE = 'CG';
    case COOK_ISLANDS = 'CK';
    case COSTA_RICA = 'CR';
    case CROATIA = 'HR';
    case CUBA = 'CU';
    case CURACAO = 'CW';
    case CYPRUS = 'CY';
    case CZECHIA = 'CZ';
    case COTE_D_IVOIRE = 'CI';
    case DENMARK = 'DK';
    case DJIBOUTI = 'DJ';
    case DOMINICA = 'DM';
    case DOMINICAN_REPUBLIC = 'DO';
    case ECUADOR = 'EC';
    case EGYPT = 'EG';
    case EL_SALVADOR = 'SV';
    case EQUATORIAL_GUINEA = 'GQ';
    case ERITREA = 'ER';
    case ESTONIA = 'EE';
    case ESWATINI = 'SZ';
    case ETHIOPIA = 'ET';
    case FALKLAND_ISLANDS_MALVINAS = 'FK';
    case FAROE_ISLANDS = 'FO';
    case FIJI = 'FJ';
    case FINLAND = 'FI';
    case FRANCE = 'FR';
    case FRENCH_GUIANA = 'GF';
    case FRENCH_POLYNESIA = 'PF';
    case FRENCH_SOUTHERN_TERRITORIES = 'TF';
    case GABON = 'GA';
    case GAMBIA = 'GM';
    case GEORGIA = 'GE';
    case GERMANY = 'DE';
    case GHANA = 'GH';
    case GIBRALTAR = 'GI';
    case GREECE = 'GR';
    case GREENLAND = 'GL';
    case GRENADA = 'GD';
    case GUADELOUPE = 'GP';
    case GUAM = 'GU';
    case GUATEMALA = 'GT';
    case GUERNSEY = 'GG';
    case GUINEA = 'GN';
    case GUINEA_BISSAU = 'GW';
    case GUYANA = 'GY';
    case HAITI = 'HT';
    case HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'HM';
    case HOLY_SEE = 'VA';
    case HONDURAS = 'HN';
    case HONG_KONG = 'HK';
    case HUNGARY = 'HU';
    case ICELAND = 'IS';
    case INDIA = 'IN';
    case INDONESIA = 'ID';
    case IRAN = 'IR';
    case IRAQ = 'IQ';
    case IRELAND = 'IE';
    case ISLE_OF_MAN = 'IM';
    case ISRAEL = 'IL';
    case ITALY = 'IT';
    case JAMAICA = 'JM';
    case JAPAN = 'JP';
    case JERSEY = 'JE';
    case JORDAN = 'JO';
    case KAZAKHSTAN = 'KZ';
    case KENYA = 'KE';
    case KIRIBATI = 'KI';
    case KUWAIT = 'KW';
    case KYRGYZSTAN = 'KG';
    case LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC = 'LA';
    case LATVIA = 'LV';
    case LEBANON = 'LB';
    case LESOTHO = 'LS';
    case LIBERIA = 'LR';
    case LIBYA = 'LY';
    case LIECHTENSTEIN = 'LI';
    case LITHUANIA = 'LT';
    case LUXEMBOURG = 'LU';
    case MACAO = 'MO';
    case MADAGASCAR = 'MG';
    case MALAWI = 'MW';
    case MALAYSIA = 'MY';
    case MALDIVES = 'MV';
    case MALI = 'ML';
    case MALTA = 'MT';
    case MARSHALL_ISLANDS = 'MH';
    case MARTINIQUE = 'MQ';
    case MAURITANIA = 'MR';
    case MAURITIUS = 'MU';
    case MAYOTTE = 'YT';
    case MEXICO = 'MX';
    case MICRONESIA = 'FM';
    case MOLDOVA = 'MD';
    case MONACO = 'MC';
    case MONGOLIA = 'MN';
    case MONTENEGRO = 'ME';
    case MONTSERRAT = 'MS';
    case MOROCCO = 'MA';
    case MOZAMBIQUE = 'MZ';
    case MYANMAR = 'MM';
    case NAMIBIA = 'NA';
    case NAURU = 'NR';
    case NEPAL = 'NP';
    case NETHERLANDS = 'NL';
    case NEW_CALEDONIA = 'NC';
    case NEW_ZEALAND = 'NZ';
    case NICARAGUA = 'NI';
    case NIGER = 'NE';
    case NIGERIA = 'NG';
    case NIUE = 'NU';
    case NORFOLK_ISLAND = 'NF';
    case NORTH_KOREA = 'KP';
    case NORTH_MACEDONIA = 'MK';
    case NORTHERN_MARIANA_ISLANDS = 'MP';
    case NORWAY = 'NO';
    case OMAN = 'OM';
    case PAKISTAN = 'PK';
    case PALAU = 'PW';
    case PALESTINE = 'PS';
    case PANAMA = 'PA';
    case PAPUA_NEW_GUINEA = 'PG';
    case PARAGUAY = 'PY';
    case PERU = 'PE';
    case PHILIPPINES = 'PH';
    case PITCAIRN = 'PN';
    case POLAND = 'PL';
    case PORTUGAL = 'PT';
    case PUERTO_RICO = 'PR';
    case QATAR = 'QA';
    case ROMANIA = 'RO';
    case RUSSIAN_FEDERATION = 'RU';
    case RWANDA = 'RW';
    case REUNION = 'RE';
    case SAINT_BARTHELEMY = 'BL';
    case SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = 'SH';
    case SAINT_KITTS_AND_NEVIS = 'KN';
    case SAINT_LUCIA = 'LC';
    case SAINT_MARTIN_FRENCH_PART = 'MF';
    case SAINT_PIERRE_AND_MIQUELON = 'PM';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'VC';
    case SAMOA = 'WS';
    case SAN_MARINO = 'SM';
    case SAO_TOME_AND_PRINCIPE = 'ST';
    case SAUDI_ARABIA = 'SA';
    case SENEGAL = 'SN';
    case SERBIA = 'RS';
    case SEYCHELLES = 'SC';
    case SIERRA_LEONE = 'SL';
    case SINGAPORE = 'SG';
    case SINT_MAARTEN_DUTCH_PART = 'SX';
    case SLOVAKIA = 'SK';
    case SLOVENIA = 'SI';
    case SOLOMON_ISLANDS = 'SB';
    case SOMALIA = 'SO';
    case SOUTH_AFRICA = 'ZA';
    case SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 'GS';
    case SOUTH_KOREA = 'KR';
    case SOUTH_SUDAN = 'SS';
    case SPAIN = 'ES';
    case SRI_LANKA = 'LK';
    case SUDAN = 'SD';
    case SURINAME = 'SR';
    case SVALBARD_AND_JAN_MAYEN = 'SJ';
    case SWEDEN = 'SE';
    case SWITZERLAND = 'CH';
    case SYRIAN_ARAB_REPUBLIC = 'SY';
    case TAIWAN = 'TW';
    case TAJIKISTAN = 'TJ';
    case TANZANIA = 'TZ';
    case THAILAND = 'TH';
    case TIMOR_LESTE = 'TL';
    case TOGO = 'TG';
    case TOKELAU = 'TK';
    case TONGA = 'TO';
    case TRINIDAD_AND_TOBAGO = 'TT';
    case TUNISIA = 'TN';
    case TURKMENISTAN = 'TM';
    case TURKS_AND_CAICOS_ISLANDS = 'TC';
    case TUVALU = 'TV';
    case TURKIYE = 'TR';
    case UGANDA = 'UG';
    case UKRAINE = 'UA';
    case UNITED_ARAB_EMIRATES = 'AE';
    case UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND = 'GB';
    case UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'UM';
    case UNITED_STATES_OF_AMERICA = 'US';
    case URUGUAY = 'UY';
    case UZBEKISTAN = 'UZ';
    case VANUATU = 'VU';
    case VENEZUELA = 'VE';
    case VIET_NAM = 'VN';
    case VIRGIN_ISLANDS_BRITISH = 'VG';
    case VIRGIN_ISLANDS_US = 'VI';
    case WALLIS_AND_FUTUNA = 'WF';
    case WESTERN_SAHARA = 'EH';
    case YEMEN = 'YE';
    case ZAMBIA = 'ZM';
    case ZIMBABWE = 'ZW';

    /**
     * @return array
     */
    public static function values(): array
    {
        return array_column(
            array: self::cases(),
            column_key: 'value'
        );
    }

    /**
     * @param mixed $value
     * @return ?self
     */
    public static function innFrom(mixed $value): ?self
    {
        if (is_null($value)) return null;
        return self::from($value);
    }

    /**
     * @return string
     */
    public function alpha2(): string
    {
        return $this->value;
    }

    /**
     * @return string
     */
    public function label(): string
    {
        return self::labels()[$this->value];
    }

    /**
     * @return string[]
     */
    public static function labels(): array
    {
        return [
            self::AFGHANISTAN->value => 'Afghanistan',
            self::ALBANIA->value => 'Albania',
            self::ALGERIA->value => 'Algeria',
            self::AMERICAN_SAMOA->value => 'American Samoa',
            self::ANDORRA->value => 'Andorra',
            self::ANGOLA->value => 'Angola',
            self::ANGUILLA->value => 'Anguilla',
            self::ANTARCTICA->value => 'Antarctica',
            self::ANTIGUA_AND_BARBUDA->value => 'Antigua and Barbuda',
            self::ARGENTINA->value => 'Argentina',
            self::ARMENIA->value => 'Armenia',
            self::ARUBA->value => 'Aruba',
            self::AUSTRALIA->value => 'Australia',
            self::AUSTRIA->value => 'Austria',
            self::AZERBAIJAN->value => 'Azerbaijan',
            self::BAHAMAS->value => 'Bahamas',
            self::BAHRAIN->value => 'Bahrain',
            self::BANGLADESH->value => 'Bangladesh',
            self::BARBADOS->value => 'Barbados',
            self::BELARUS->value => 'Belarus',
            self::BELGIUM->value => 'Belgium',
            self::BELIZE->value => 'Belize',
            self::BENIN->value => 'Benin',
            self::BERMUDA->value => 'Bermuda',
            self::BHUTAN->value => 'Bhutan',
            self::BOLIVIA->value => 'Bolivia',
            self::BONAIRE_SINT_EUSTATIUS_AND_SABA->value => 'Bonaire, Sint Eustatius and Saba',
            self::BOSNIA_AND_HERZEGOVINA->value => 'Bosnia and Herzegovina',
            self::BOTSWANA->value => 'Botswana',
            self::BOUVET_ISLAND->value => 'Bouvet Island',
            self::BRAZIL->value => 'Brazil',
            self::BRITISH_INDIAN_OCEAN_TERRITORY->value => 'British Indian Ocean Territory',
            self::BRUNEI_DARUSSALAM->value => 'Brunei Darussalam',
            self::BULGARIA->value => 'Bulgaria',
            self::BURKINA_FASO->value => 'Burkina Faso',
            self::BURUNDI->value => 'Burundi',
            self::CABO_VERDE->value => 'Cabo Verde',
            self::CAMBODIA->value => 'Cambodia',
            self::CAMEROON->value => 'Cameroon',
            self::CANADA->value => 'Canada',
            self::CAYMAN_ISLANDS->value => 'Cayman Islands',
            self::CENTRAL_AFRICAN_REPUBLIC->value => 'Central African Republic',
            self::CHAD->value => 'Chad',
            self::CHILE->value => 'Chile',
            self::CHINA->value => 'China',
            self::CHRISTMAS_ISLAND->value => 'Christmas Island',
            self::COCOS_KEELING_ISLANDS->value => 'Cocos (Keeling) Islands',
            self::COLOMBIA->value => 'Colombia',
            self::COMOROS->value => 'Comoros',
            self::CONGO_KINSHASA->value => 'Congo (Kinshasa)',
            self::CONGO_BRAZZAVILLE->value => 'Congo (Brazzaville)',
            self::COOK_ISLANDS->value => 'Cook Islands',
            self::COSTA_RICA->value => 'Costa Rica',
            self::CROATIA->value => 'Croatia',
            self::CUBA->value => 'Cuba',
            self::CURACAO->value => 'Curaçao',
            self::CYPRUS->value => 'Cyprus',
            self::CZECHIA->value => 'Czechia',
            self::COTE_D_IVOIRE->value => 'Côte d\'Ivoire',
            self::DENMARK->value => 'Denmark',
            self::DJIBOUTI->value => 'Djibouti',
            self::DOMINICA->value => 'Dominica',
            self::DOMINICAN_REPUBLIC->value => 'Dominican Republic',
            self::ECUADOR->value => 'Ecuador',
            self::EGYPT->value => 'Egypt',
            self::EL_SALVADOR->value => 'El Salvador',
            self::EQUATORIAL_GUINEA->value => 'Equatorial Guinea',
            self::ERITREA->value => 'Eritrea',
            self::ESTONIA->value => 'Estonia',
            self::ESWATINI->value => 'Eswatini',
            self::ETHIOPIA->value => 'Ethiopia',
            self::FALKLAND_ISLANDS_MALVINAS->value => 'Falkland Islands (Malvinas)',
            self::FAROE_ISLANDS->value => 'Faroe Islands',
            self::FIJI->value => 'Fiji',
            self::FINLAND->value => 'Finland',
            self::FRANCE->value => 'France',
            self::FRENCH_GUIANA->value => 'French Guiana',
            self::FRENCH_POLYNESIA->value => 'French Polynesia',
            self::FRENCH_SOUTHERN_TERRITORIES->value => 'French Southern Territories',
            self::GABON->value => 'Gabon',
            self::GAMBIA->value => 'Gambia',
            self::GEORGIA->value => 'Georgia',
            self::GERMANY->value => 'Germany',
            self::GHANA->value => 'Ghana',
            self::GIBRALTAR->value => 'Gibraltar',
            self::GREECE->value => 'Greece',
            self::GREENLAND->value => 'Greenland',
            self::GRENADA->value => 'Grenada',
            self::GUADELOUPE->value => 'Guadeloupe',
            self::GUAM->value => 'Guam',
            self::GUATEMALA->value => 'Guatemala',
            self::GUERNSEY->value => 'Guernsey',
            self::GUINEA->value => 'Guinea',
            self::GUINEA_BISSAU->value => 'Guinea-Bissau',
            self::GUYANA->value => 'Guyana',
            self::HAITI->value => 'Haiti',
            self::HEARD_ISLAND_AND_MCDONALD_ISLANDS->value => 'Heard Island and McDonald Islands',
            self::HOLY_SEE->value => 'Holy See',
            self::HONDURAS->value => 'Honduras',
            self::HONG_KONG->value => 'Hong Kong',
            self::HUNGARY->value => 'Hungary',
            self::ICELAND->value => 'Iceland',
            self::INDIA->value => 'India',
            self::INDONESIA->value => 'Indonesia',
            self::IRAN->value => 'Iran',
            self::IRAQ->value => 'Iraq',
            self::IRELAND->value => 'Ireland',
            self::ISLE_OF_MAN->value => 'Isle of Man',
            self::ISRAEL->value => 'Israel',
            self::ITALY->value => 'Italy',
            self::JAMAICA->value => 'Jamaica',
            self::JAPAN->value => 'Japan',
            self::JERSEY->value => 'Jersey',
            self::JORDAN->value => 'Jordan',
            self::KAZAKHSTAN->value => 'Kazakhstan',
            self::KENYA->value => 'Kenya',
            self::KIRIBATI->value => 'Kiribati',
            self::KUWAIT->value => 'Kuwait',
            self::KYRGYZSTAN->value => 'Kyrgyzstan',
            self::LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC->value => 'Lao People\'s Democratic Republic',
            self::LATVIA->value => 'Latvia',
            self::LEBANON->value => 'Lebanon',
            self::LESOTHO->value => 'Lesotho',
            self::LIBERIA->value => 'Liberia',
            self::LIBYA->value => 'Libya',
            self::LIECHTENSTEIN->value => 'Liechtenstein',
            self::LITHUANIA->value => 'Lithuania',
            self::LUXEMBOURG->value => 'Luxembourg',
            self::MACAO->value => 'Macao',
            self::MADAGASCAR->value => 'Madagascar',
            self::MALAWI->value => 'Malawi',
            self::MALAYSIA->value => 'Malaysia',
            self::MALDIVES->value => 'Maldives',
            self::MALI->value => 'Mali',
            self::MALTA->value => 'Malta',
            self::MARSHALL_ISLANDS->value => 'Marshall Islands',
            self::MARTINIQUE->value => 'Martinique',
            self::MAURITANIA->value => 'Mauritania',
            self::MAURITIUS->value => 'Mauritius',
            self::MAYOTTE->value => 'Mayotte',
            self::MEXICO->value => 'Mexico',
            self::MICRONESIA->value => 'Micronesia',
            self::MOLDOVA->value => 'Moldova',
            self::MONACO->value => 'Monaco',
            self::MONGOLIA->value => 'Mongolia',
            self::MONTENEGRO->value => 'Montenegro',
            self::MONTSERRAT->value => 'Montserrat',
            self::MOROCCO->value => 'Morocco',
            self::MOZAMBIQUE->value => 'Mozambique',
            self::MYANMAR->value => 'Myanmar',
            self::NAMIBIA->value => 'Namibia',
            self::NAURU->value => 'Nauru',
            self::NEPAL->value => 'Nepal',
            self::NETHERLANDS->value => 'Netherlands',
            self::NEW_CALEDONIA->value => 'New Caledonia',
            self::NEW_ZEALAND->value => 'New Zealand',
            self::NICARAGUA->value => 'Nicaragua',
            self::NIGER->value => 'Niger',
            self::NIGERIA->value => 'Nigeria',
            self::NIUE->value => 'Niue',
            self::NORFOLK_ISLAND->value => 'Norfolk Island',
            self::NORTH_KOREA->value => 'North Korea',
            self::NORTH_MACEDONIA->value => 'North Macedonia',
            self::NORTHERN_MARIANA_ISLANDS->value => 'Northern Mariana Islands',
            self::NORWAY->value => 'Norway',
            self::OMAN->value => 'Oman',
            self::PAKISTAN->value => 'Pakistan',
            self::PALAU->value => 'Palau',
            self::PALESTINE->value => 'Palestine',
            self::PANAMA->value => 'Panama',
            self::PAPUA_NEW_GUINEA->value => 'Papua New Guinea',
            self::PARAGUAY->value => 'Paraguay',
            self::PERU->value => 'Peru',
            self::PHILIPPINES->value => 'Philippines',
            self::PITCAIRN->value => 'Pitcairn',
            self::POLAND->value => 'Poland',
            self::PORTUGAL->value => 'Portugal',
            self::PUERTO_RICO->value => 'Puerto Rico',
            self::QATAR->value => 'Qatar',
            self::ROMANIA->value => 'Romania',
            self::RUSSIAN_FEDERATION->value => 'Russian Federation',
            self::RWANDA->value => 'Rwanda',
            self::REUNION->value => 'Réunion',
            self::SAINT_BARTHELEMY->value => 'Saint Barthélemy',
            self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA->value => 'Saint Helena, Ascension and Tristan da Cunha',
            self::SAINT_KITTS_AND_NEVIS->value => 'Saint Kitts and Nevis',
            self::SAINT_LUCIA->value => 'Saint Lucia',
            self::SAINT_MARTIN_FRENCH_PART->value => 'Saint Martin (French part)',
            self::SAINT_PIERRE_AND_MIQUELON->value => 'Saint Pierre and Miquelon',
            self::SAINT_VINCENT_AND_THE_GRENADINES->value => 'Saint Vincent and the Grenadines',
            self::SAMOA->value => 'Samoa',
            self::SAN_MARINO->value => 'San Marino',
            self::SAO_TOME_AND_PRINCIPE->value => 'Sao Tome and Principe',
            self::SAUDI_ARABIA->value => 'Saudi Arabia',
            self::SENEGAL->value => 'Senegal',
            self::SERBIA->value => 'Serbia',
            self::SEYCHELLES->value => 'Seychelles',
            self::SIERRA_LEONE->value => 'Sierra Leone',
            self::SINGAPORE->value => 'Singapore',
            self::SINT_MAARTEN_DUTCH_PART->value => 'Sint Maarten (Dutch part)',
            self::SLOVAKIA->value => 'Slovakia',
            self::SLOVENIA->value => 'Slovenia',
            self::SOLOMON_ISLANDS->value => 'Solomon Islands',
            self::SOMALIA->value => 'Somalia',
            self::SOUTH_AFRICA->value => 'South Africa',
            self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS->value => 'South Georgia and the South Sandwich Islands',
            self::SOUTH_KOREA->value => 'South Korea',
            self::SOUTH_SUDAN->value => 'South Sudan',
            self::SPAIN->value => 'Spain',
            self::SRI_LANKA->value => 'Sri Lanka',
            self::SUDAN->value => 'Sudan',
            self::SURINAME->value => 'Suriname',
            self::SVALBARD_AND_JAN_MAYEN->value => 'Svalbard and Jan Mayen',
            self::SWEDEN->value => 'Sweden',
            self::SWITZERLAND->value => 'Switzerland',
            self::SYRIAN_ARAB_REPUBLIC->value => 'Syrian Arab Republic',
            self::TAIWAN->value => 'Taiwan',
            self::TAJIKISTAN->value => 'Tajikistan',
            self::TANZANIA->value => 'Tanzania',
            self::THAILAND->value => 'Thailand',
            self::TIMOR_LESTE->value => 'Timor-Leste',
            self::TOGO->value => 'Togo',
            self::TOKELAU->value => 'Tokelau',
            self::TONGA->value => 'Tonga',
            self::TRINIDAD_AND_TOBAGO->value => 'Trinidad and Tobago',
            self::TUNISIA->value => 'Tunisia',
            self::TURKMENISTAN->value => 'Turkmenistan',
            self::TURKS_AND_CAICOS_ISLANDS->value => 'Turks and Caicos Islands',
            self::TUVALU->value => 'Tuvalu',
            self::TURKIYE->value => 'Türkiye',
            self::UGANDA->value => 'Uganda',
            self::UKRAINE->value => 'Ukraine',
            self::UNITED_ARAB_EMIRATES->value => 'United Arab Emirates',
            self::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND->value => 'United Kingdom of Great Britain and Northern Ireland',
            self::UNITED_STATES_MINOR_OUTLYING_ISLANDS->value => 'United States Minor Outlying Islands',
            self::UNITED_STATES_OF_AMERICA->value => 'United States of America',
            self::URUGUAY->value => 'Uruguay',
            self::UZBEKISTAN->value => 'Uzbekistan',
            self::VANUATU->value => 'Vanuatu',
            self::VENEZUELA->value => 'Venezuela',
            self::VIET_NAM->value => 'Viet Nam',
            self::VIRGIN_ISLANDS_BRITISH->value => 'Virgin Islands (British)',
            self::VIRGIN_ISLANDS_US->value => 'Virgin Islands (U.S.)',
            self::WALLIS_AND_FUTUNA->value => 'Wallis and Futuna',
            self::WESTERN_SAHARA->value => 'Western Sahara',
            self::YEMEN->value => 'Yemen',
            self::ZAMBIA->value => 'Zambia',
            self::ZIMBABWE->value => 'Zimbabwe'
        ];
    }

    /**
     * @return string
     */
    public function alpha3(): string
    {
        return self::alpha3Codes()[$this->value];
    }

    /**
     * @return string[]
     */
    public static function alpha3Codes(): array
    {
        return [
            self::AFGHANISTAN->value => 'AFG',
            self::ALBANIA->value => 'ALB',
            self::ALGERIA->value => 'DZA',
            self::AMERICAN_SAMOA->value => 'ASM',
            self::ANDORRA->value => 'AND',
            self::ANGOLA->value => 'AGO',
            self::ANGUILLA->value => 'AIA',
            self::ANTARCTICA->value => 'ATA',
            self::ANTIGUA_AND_BARBUDA->value => 'ATG',
            self::ARGENTINA->value => 'ARG',
            self::ARMENIA->value => 'ARM',
            self::ARUBA->value => 'ABW',
            self::AUSTRALIA->value => 'AUS',
            self::AUSTRIA->value => 'AUT',
            self::AZERBAIJAN->value => 'AZE',
            self::BAHAMAS->value => 'BHS',
            self::BAHRAIN->value => 'BHR',
            self::BANGLADESH->value => 'BGD',
            self::BARBADOS->value => 'BRB',
            self::BELARUS->value => 'BLR',
            self::BELGIUM->value => 'BEL',
            self::BELIZE->value => 'BLZ',
            self::BENIN->value => 'BEN',
            self::BERMUDA->value => 'BMU',
            self::BHUTAN->value => 'BTN',
            self::BOLIVIA->value => 'BOL',
            self::BONAIRE_SINT_EUSTATIUS_AND_SABA->value => 'BES',
            self::BOSNIA_AND_HERZEGOVINA->value => 'BIH',
            self::BOTSWANA->value => 'BWA',
            self::BOUVET_ISLAND->value => 'BVT',
            self::BRAZIL->value => 'BRA',
            self::BRITISH_INDIAN_OCEAN_TERRITORY->value => 'IOT',
            self::BRUNEI_DARUSSALAM->value => 'BRN',
            self::BULGARIA->value => 'BGR',
            self::BURKINA_FASO->value => 'BFA',
            self::BURUNDI->value => 'BDI',
            self::CABO_VERDE->value => 'CPV',
            self::CAMBODIA->value => 'KHM',
            self::CAMEROON->value => 'CMR',
            self::CANADA->value => 'CAN',
            self::CAYMAN_ISLANDS->value => 'CYM',
            self::CENTRAL_AFRICAN_REPUBLIC->value => 'CAF',
            self::CHAD->value => 'TCD',
            self::CHILE->value => 'CHL',
            self::CHINA->value => 'CHN',
            self::CHRISTMAS_ISLAND->value => 'CXR',
            self::COCOS_KEELING_ISLANDS->value => 'CCK',
            self::COLOMBIA->value => 'COL',
            self::COMOROS->value => 'COM',
            self::CONGO_KINSHASA->value => 'COD',
            self::CONGO_BRAZZAVILLE->value => 'COG',
            self::COOK_ISLANDS->value => 'COK',
            self::COSTA_RICA->value => 'CRI',
            self::CROATIA->value => 'HRV',
            self::CUBA->value => 'CUB',
            self::CURACAO->value => 'CUW',
            self::CYPRUS->value => 'CYP',
            self::CZECHIA->value => 'CZE',
            self::COTE_D_IVOIRE->value => 'CIV',
            self::DENMARK->value => 'DNK',
            self::DJIBOUTI->value => 'DJI',
            self::DOMINICA->value => 'DMA',
            self::DOMINICAN_REPUBLIC->value => 'DOM',
            self::ECUADOR->value => 'ECU',
            self::EGYPT->value => 'EGY',
            self::EL_SALVADOR->value => 'SLV',
            self::EQUATORIAL_GUINEA->value => 'GNQ',
            self::ERITREA->value => 'ERI',
            self::ESTONIA->value => 'EST',
            self::ESWATINI->value => 'SWZ',
            self::ETHIOPIA->value => 'ETH',
            self::FALKLAND_ISLANDS_MALVINAS->value => 'FLK',
            self::FAROE_ISLANDS->value => 'FRO',
            self::FIJI->value => 'FJI',
            self::FINLAND->value => 'FIN',
            self::FRANCE->value => 'FRA',
            self::FRENCH_GUIANA->value => 'GUF',
            self::FRENCH_POLYNESIA->value => 'PYF',
            self::FRENCH_SOUTHERN_TERRITORIES->value => 'ATF',
            self::GABON->value => 'GAB',
            self::GAMBIA->value => 'GMB',
            self::GEORGIA->value => 'GEO',
            self::GERMANY->value => 'DEU',
            self::GHANA->value => 'GHA',
            self::GIBRALTAR->value => 'GIB',
            self::GREECE->value => 'GRC',
            self::GREENLAND->value => 'GRL',
            self::GRENADA->value => 'GRD',
            self::GUADELOUPE->value => 'GLP',
            self::GUAM->value => 'GUM',
            self::GUATEMALA->value => 'GTM',
            self::GUERNSEY->value => 'GGY',
            self::GUINEA->value => 'GIN',
            self::GUINEA_BISSAU->value => 'GNB',
            self::GUYANA->value => 'GUY',
            self::HAITI->value => 'HTI',
            self::HEARD_ISLAND_AND_MCDONALD_ISLANDS->value => 'HMD',
            self::HOLY_SEE->value => 'VAT',
            self::HONDURAS->value => 'HND',
            self::HONG_KONG->value => 'HKG',
            self::HUNGARY->value => 'HUN',
            self::ICELAND->value => 'ISL',
            self::INDIA->value => 'IND',
            self::INDONESIA->value => 'IDN',
            self::IRAN->value => 'IRN',
            self::IRAQ->value => 'IRQ',
            self::IRELAND->value => 'IRL',
            self::ISLE_OF_MAN->value => 'IMN',
            self::ISRAEL->value => 'ISR',
            self::ITALY->value => 'ITA',
            self::JAMAICA->value => 'JAM',
            self::JAPAN->value => 'JPN',
            self::JERSEY->value => 'JEY',
            self::JORDAN->value => 'JOR',
            self::KAZAKHSTAN->value => 'KAZ',
            self::KENYA->value => 'KEN',
            self::KIRIBATI->value => 'KIR',
            self::KUWAIT->value => 'PRK',
            self::KYRGYZSTAN->value => 'KOR',
            self::LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC->value => 'KWT',
            self::LATVIA->value => 'KGZ',
            self::LEBANON->value => 'LAO',
            self::LESOTHO->value => 'LVA',
            self::LIBERIA->value => 'LBN',
            self::LIBYA->value => 'LSO',
            self::LIECHTENSTEIN->value => 'LBR',
            self::LITHUANIA->value => 'LBY',
            self::LUXEMBOURG->value => 'LIE',
            self::MACAO->value => 'LTU',
            self::MADAGASCAR->value => 'LUX',
            self::MALAWI->value => 'MAC',
            self::MALAYSIA->value => 'MDG',
            self::MALDIVES->value => 'MWI',
            self::MALI->value => 'MYS',
            self::MALTA->value => 'MDV',
            self::MARSHALL_ISLANDS->value => 'MLI',
            self::MARTINIQUE->value => 'MLT',
            self::MAURITANIA->value => 'MHL',
            self::MAURITIUS->value => 'MTQ',
            self::MAYOTTE->value => 'MRT',
            self::MEXICO->value => 'MUS',
            self::MICRONESIA->value => 'MYT',
            self::MOLDOVA->value => 'MEX',
            self::MONACO->value => 'FSM',
            self::MONGOLIA->value => 'MDA',
            self::MONTENEGRO->value => 'MCO',
            self::MONTSERRAT->value => 'MNG',
            self::MOROCCO->value => 'MNE',
            self::MOZAMBIQUE->value => 'MSR',
            self::MYANMAR->value => 'MAR',
            self::NAMIBIA->value => 'MOZ',
            self::NAURU->value => 'MMR',
            self::NEPAL->value => 'NAM',
            self::NETHERLANDS->value => 'NRU',
            self::NEW_CALEDONIA->value => 'NPL',
            self::NEW_ZEALAND->value => 'NLD',
            self::NICARAGUA->value => 'NCL',
            self::NIGER->value => 'NZL',
            self::NIGERIA->value => 'NIC',
            self::NIUE->value => 'NER',
            self::NORFOLK_ISLAND->value => 'NGA',
            self::NORTH_KOREA->value => 'NIU',
            self::NORTH_MACEDONIA->value => 'NFK',
            self::NORTHERN_MARIANA_ISLANDS->value => 'MKD',
            self::NORWAY->value => 'MNP',
            self::OMAN->value => 'NOR',
            self::PAKISTAN->value => 'OMN',
            self::PALAU->value => 'PAK',
            self::PALESTINE->value => 'PLW',
            self::PANAMA->value => 'PSE',
            self::PAPUA_NEW_GUINEA->value => 'PAN',
            self::PARAGUAY->value => 'PNG',
            self::PERU->value => 'PRY',
            self::PHILIPPINES->value => 'PER',
            self::PITCAIRN->value => 'PHL',
            self::POLAND->value => 'PCN',
            self::PORTUGAL->value => 'POL',
            self::PUERTO_RICO->value => 'PRT',
            self::QATAR->value => 'PRI',
            self::ROMANIA->value => 'QAT',
            self::RUSSIAN_FEDERATION->value => 'ROU',
            self::RWANDA->value => 'RUS',
            self::REUNION->value => 'RWA',
            self::SAINT_BARTHELEMY->value => 'REU',
            self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA->value => 'BLM',
            self::SAINT_KITTS_AND_NEVIS->value => 'SHN',
            self::SAINT_LUCIA->value => 'KNA',
            self::SAINT_MARTIN_FRENCH_PART->value => 'LCA',
            self::SAINT_PIERRE_AND_MIQUELON->value => 'MAF',
            self::SAINT_VINCENT_AND_THE_GRENADINES->value => 'SPM',
            self::SAMOA->value => 'VCT',
            self::SAN_MARINO->value => 'WSM',
            self::SAO_TOME_AND_PRINCIPE->value => 'SMR',
            self::SAUDI_ARABIA->value => 'STP',
            self::SENEGAL->value => 'SAU',
            self::SERBIA->value => 'SEN',
            self::SEYCHELLES->value => 'SRB',
            self::SIERRA_LEONE->value => 'SYC',
            self::SINGAPORE->value => 'SLE',
            self::SINT_MAARTEN_DUTCH_PART->value => 'SGP',
            self::SLOVAKIA->value => 'SXM',
            self::SLOVENIA->value => 'SVK',
            self::SOLOMON_ISLANDS->value => 'SVN',
            self::SOMALIA->value => 'SLB',
            self::SOUTH_AFRICA->value => 'SOM',
            self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS->value => 'ZAF',
            self::SOUTH_KOREA->value => 'SGS',
            self::SOUTH_SUDAN->value => 'SSD',
            self::SPAIN->value => 'ESP',
            self::SRI_LANKA->value => 'LKA',
            self::SUDAN->value => 'SDN',
            self::SURINAME->value => 'SUR',
            self::SVALBARD_AND_JAN_MAYEN->value => 'SJM',
            self::SWEDEN->value => 'SWE',
            self::SWITZERLAND->value => 'CHE',
            self::SYRIAN_ARAB_REPUBLIC->value => 'SYR',
            self::TAIWAN->value => 'TWN',
            self::TAJIKISTAN->value => 'TJK',
            self::TANZANIA->value => 'TZA',
            self::THAILAND->value => 'THA',
            self::TIMOR_LESTE->value => 'TLS',
            self::TOGO->value => 'TGO',
            self::TOKELAU->value => 'TKL',
            self::TONGA->value => 'TON',
            self::TRINIDAD_AND_TOBAGO->value => 'TTO',
            self::TUNISIA->value => 'TUN',
            self::TURKMENISTAN->value => 'TKM',
            self::TURKS_AND_CAICOS_ISLANDS->value => 'TCA',
            self::TUVALU->value => 'TUV',
            self::TURKIYE->value => 'TUR',
            self::UGANDA->value => 'UGA',
            self::UKRAINE->value => 'UKR',
            self::UNITED_ARAB_EMIRATES->value => 'ARE',
            self::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND->value => 'GBR',
            self::UNITED_STATES_MINOR_OUTLYING_ISLANDS->value => 'UMI',
            self::UNITED_STATES_OF_AMERICA->value => 'USA',
            self::URUGUAY->value => 'URY',
            self::UZBEKISTAN->value => 'UZB',
            self::VANUATU->value => 'VUT',
            self::VENEZUELA->value => 'VEN',
            self::VIET_NAM->value => 'VNM',
            self::VIRGIN_ISLANDS_BRITISH->value => 'VGB',
            self::VIRGIN_ISLANDS_US->value => 'VIR',
            self::WALLIS_AND_FUTUNA->value => 'WLF',
            self::WESTERN_SAHARA->value => 'ESH',
            self::YEMEN->value => 'YEM',
            self::ZAMBIA->value => 'ZMB',
            self::ZIMBABWE->value => 'ZWE',
        ];
    }

    /**
     * @return string
     */
    public function numeric(): string
    {
        return self::numericCodes()[$this->value];
    }

    /**
     * @return string[]
     */
    public static function numericCodes(): array
    {
        return [
            self::AFGHANISTAN->value => '004',
            self::ALBANIA->value => '008',
            self::ALGERIA->value => '012',
            self::AMERICAN_SAMOA->value => '016',
            self::ANDORRA->value => '020',
            self::ANGOLA->value => '024',
            self::ANGUILLA->value => '660',
            self::ANTARCTICA->value => '010',
            self::ANTIGUA_AND_BARBUDA->value => '028',
            self::ARGENTINA->value => '032',
            self::ARMENIA->value => '051',
            self::ARUBA->value => '533',
            self::AUSTRALIA->value => '036',
            self::AUSTRIA->value => '040',
            self::AZERBAIJAN->value => '031',
            self::BAHAMAS->value => '044',
            self::BAHRAIN->value => '048',
            self::BANGLADESH->value => '050',
            self::BARBADOS->value => '052',
            self::BELARUS->value => '112',
            self::BELGIUM->value => '056',
            self::BELIZE->value => '084',
            self::BENIN->value => '204',
            self::BERMUDA->value => '060',
            self::BHUTAN->value => '064',
            self::BOLIVIA->value => '068',
            self::BONAIRE_SINT_EUSTATIUS_AND_SABA->value => '535',
            self::BOSNIA_AND_HERZEGOVINA->value => '070',
            self::BOTSWANA->value => '072',
            self::BOUVET_ISLAND->value => '074',
            self::BRAZIL->value => '076',
            self::BRITISH_INDIAN_OCEAN_TERRITORY->value => '086',
            self::BRUNEI_DARUSSALAM->value => '096',
            self::BULGARIA->value => '100',
            self::BURKINA_FASO->value => '854',
            self::BURUNDI->value => '108',
            self::CABO_VERDE->value => '132',
            self::CAMBODIA->value => '116',
            self::CAMEROON->value => '120',
            self::CANADA->value => '124',
            self::CAYMAN_ISLANDS->value => '136',
            self::CENTRAL_AFRICAN_REPUBLIC->value => '140',
            self::CHAD->value => '148',
            self::CHILE->value => '152',
            self::CHINA->value => '156',
            self::CHRISTMAS_ISLAND->value => '162',
            self::COCOS_KEELING_ISLANDS->value => '166',
            self::COLOMBIA->value => '170',
            self::COMOROS->value => '174',
            self::CONGO_KINSHASA->value => '180',
            self::CONGO_BRAZZAVILLE->value => '178',
            self::COOK_ISLANDS->value => '184',
            self::COSTA_RICA->value => '188',
            self::CROATIA->value => '191',
            self::CUBA->value => '192',
            self::CURACAO->value => '531',
            self::CYPRUS->value => '196',
            self::CZECHIA->value => '203',
            self::COTE_D_IVOIRE->value => '384',
            self::DENMARK->value => '208',
            self::DJIBOUTI->value => '262',
            self::DOMINICA->value => '212',
            self::DOMINICAN_REPUBLIC->value => '214',
            self::ECUADOR->value => '218',
            self::EGYPT->value => '818',
            self::EL_SALVADOR->value => '222',
            self::EQUATORIAL_GUINEA->value => '226',
            self::ERITREA->value => '232',
            self::ESTONIA->value => '233',
            self::ESWATINI->value => '748',
            self::ETHIOPIA->value => '231',
            self::FALKLAND_ISLANDS_MALVINAS->value => '238',
            self::FAROE_ISLANDS->value => '234',
            self::FIJI->value => '242',
            self::FINLAND->value => '246',
            self::FRANCE->value => '250',
            self::FRENCH_GUIANA->value => '254',
            self::FRENCH_POLYNESIA->value => '258',
            self::FRENCH_SOUTHERN_TERRITORIES->value => '260',
            self::GABON->value => '266',
            self::GAMBIA->value => '270',
            self::GEORGIA->value => '268',
            self::GERMANY->value => '276',
            self::GHANA->value => '288',
            self::GIBRALTAR->value => '292',
            self::GREECE->value => '300',
            self::GREENLAND->value => '304',
            self::GRENADA->value => '308',
            self::GUADELOUPE->value => '312',
            self::GUAM->value => '316',
            self::GUATEMALA->value => '320',
            self::GUERNSEY->value => '831',
            self::GUINEA->value => '324',
            self::GUINEA_BISSAU->value => '624',
            self::GUYANA->value => '328',
            self::HAITI->value => '332',
            self::HEARD_ISLAND_AND_MCDONALD_ISLANDS->value => '334',
            self::HOLY_SEE->value => '336',
            self::HONDURAS->value => '340',
            self::HONG_KONG->value => '344',
            self::HUNGARY->value => '348',
            self::ICELAND->value => '352',
            self::INDIA->value => '356',
            self::INDONESIA->value => '360',
            self::IRAN->value => '364',
            self::IRAQ->value => '368',
            self::IRELAND->value => '372',
            self::ISLE_OF_MAN->value => '833',
            self::ISRAEL->value => '376',
            self::ITALY->value => '380',
            self::JAMAICA->value => '388',
            self::JAPAN->value => '392',
            self::JERSEY->value => '832',
            self::JORDAN->value => '400',
            self::KAZAKHSTAN->value => '398',
            self::KENYA->value => '404',
            self::KIRIBATI->value => '296',
            self::KUWAIT->value => '408',
            self::KYRGYZSTAN->value => '410',
            self::LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC->value => '414',
            self::LATVIA->value => '417',
            self::LEBANON->value => '418',
            self::LESOTHO->value => '428',
            self::LIBERIA->value => '422',
            self::LIBYA->value => '426',
            self::LIECHTENSTEIN->value => '430',
            self::LITHUANIA->value => '434',
            self::LUXEMBOURG->value => '438',
            self::MACAO->value => '440',
            self::MADAGASCAR->value => '442',
            self::MALAWI->value => '446',
            self::MALAYSIA->value => '450',
            self::MALDIVES->value => '454',
            self::MALI->value => '458',
            self::MALTA->value => '462',
            self::MARSHALL_ISLANDS->value => '466',
            self::MARTINIQUE->value => '470',
            self::MAURITANIA->value => '584',
            self::MAURITIUS->value => '474',
            self::MAYOTTE->value => '478',
            self::MEXICO->value => '480',
            self::MICRONESIA->value => '175',
            self::MOLDOVA->value => '484',
            self::MONACO->value => '583',
            self::MONGOLIA->value => '498',
            self::MONTENEGRO->value => '492',
            self::MONTSERRAT->value => '496',
            self::MOROCCO->value => '499',
            self::MOZAMBIQUE->value => '500',
            self::MYANMAR->value => '504',
            self::NAMIBIA->value => '508',
            self::NAURU->value => '104',
            self::NEPAL->value => '516',
            self::NETHERLANDS->value => '520',
            self::NEW_CALEDONIA->value => '524',
            self::NEW_ZEALAND->value => '528',
            self::NICARAGUA->value => '540',
            self::NIGER->value => '554',
            self::NIGERIA->value => '558',
            self::NIUE->value => '562',
            self::NORFOLK_ISLAND->value => '566',
            self::NORTH_KOREA->value => '570',
            self::NORTH_MACEDONIA->value => '574',
            self::NORTHERN_MARIANA_ISLANDS->value => '807',
            self::NORWAY->value => '580',
            self::OMAN->value => '578',
            self::PAKISTAN->value => '512',
            self::PALAU->value => '586',
            self::PALESTINE->value => '585',
            self::PANAMA->value => '275',
            self::PAPUA_NEW_GUINEA->value => '591',
            self::PARAGUAY->value => '598',
            self::PERU->value => '600',
            self::PHILIPPINES->value => '604',
            self::PITCAIRN->value => '608',
            self::POLAND->value => '612',
            self::PORTUGAL->value => '616',
            self::PUERTO_RICO->value => '620',
            self::QATAR->value => '630',
            self::ROMANIA->value => '634',
            self::RUSSIAN_FEDERATION->value => '642',
            self::RWANDA->value => '643',
            self::REUNION->value => '646',
            self::SAINT_BARTHELEMY->value => '638',
            self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA->value => '652',
            self::SAINT_KITTS_AND_NEVIS->value => '654',
            self::SAINT_LUCIA->value => '659',
            self::SAINT_MARTIN_FRENCH_PART->value => '662',
            self::SAINT_PIERRE_AND_MIQUELON->value => '663',
            self::SAINT_VINCENT_AND_THE_GRENADINES->value => '666',
            self::SAMOA->value => '670',
            self::SAN_MARINO->value => '882',
            self::SAO_TOME_AND_PRINCIPE->value => '674',
            self::SAUDI_ARABIA->value => '678',
            self::SENEGAL->value => '682',
            self::SERBIA->value => '686',
            self::SEYCHELLES->value => '688',
            self::SIERRA_LEONE->value => '690',
            self::SINGAPORE->value => '694',
            self::SINT_MAARTEN_DUTCH_PART->value => '702',
            self::SLOVAKIA->value => '534',
            self::SLOVENIA->value => '703',
            self::SOLOMON_ISLANDS->value => '705',
            self::SOMALIA->value => '090',
            self::SOUTH_AFRICA->value => '706',
            self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS->value => '710',
            self::SOUTH_KOREA->value => '239',
            self::SOUTH_SUDAN->value => '728',
            self::SPAIN->value => '724',
            self::SRI_LANKA->value => '144',
            self::SUDAN->value => '729',
            self::SURINAME->value => '740',
            self::SVALBARD_AND_JAN_MAYEN->value => '744',
            self::SWEDEN->value => '752',
            self::SWITZERLAND->value => '756',
            self::SYRIAN_ARAB_REPUBLIC->value => '760',
            self::TAIWAN->value => '158',
            self::TAJIKISTAN->value => '762',
            self::TANZANIA->value => '834',
            self::THAILAND->value => '764',
            self::TIMOR_LESTE->value => '626',
            self::TOGO->value => '768',
            self::TOKELAU->value => '772',
            self::TONGA->value => '776',
            self::TRINIDAD_AND_TOBAGO->value => '780',
            self::TUNISIA->value => '788',
            self::TURKMENISTAN->value => '795',
            self::TURKS_AND_CAICOS_ISLANDS->value => '796',
            self::TUVALU->value => '798',
            self::TURKIYE->value => '792',
            self::UGANDA->value => '800',
            self::UKRAINE->value => '804',
            self::UNITED_ARAB_EMIRATES->value => '784',
            self::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND->value => '826',
            self::UNITED_STATES_MINOR_OUTLYING_ISLANDS->value => '581',
            self::UNITED_STATES_OF_AMERICA->value => '840',
            self::URUGUAY->value => '858',
            self::UZBEKISTAN->value => '860',
            self::VANUATU->value => '548',
            self::VENEZUELA->value => '862',
            self::VIET_NAM->value => '704',
            self::VIRGIN_ISLANDS_BRITISH->value => '092',
            self::VIRGIN_ISLANDS_US->value => '850',
            self::WALLIS_AND_FUTUNA->value => '876',
            self::WESTERN_SAHARA->value => '732',
            self::YEMEN->value => '887',
            self::ZAMBIA->value => '894',
            self::ZIMBABWE->value => '716',
        ];
    }
}
